=== waanlabs/gitcoffee/modules/migration/schemas/milestone.json
{
    "title": "Milestone",
    "description": "Milestone associated to a repository within a forge.",

    "type": "array",
    "items": {
	"type": "object",
	"additionalProperties": false,
	"properties": {
	    "title": {
		"description": "Short description.",
		"type": "string"
	    },
	    "description": {
		"description": "Long, multiline, description.",
		"type": "string"
	    },
	    "deadline": {
		"description": "Deadline after which the milestone is overdue.",
		"type": "string",
		"format": "date-time"
	    },
	    "created": {
		"description": "Creation time.",
		"type": "string",
		"format": "date-time"
	    },
	    "updated": {
		"description": "Last update time.",
		"type": "string",
		"format": "date-time"
	    },
	    "closed": {
		"description": "The last time 'state' changed to 'closed'.",
		"anyOf": [
		    {
			"type": "string",
			"format": "date-time"
		    },
		    {
			"type": "null"
		    }
		]
	    },
	    "state": {
		"description": "A 'closed' issue will not see any activity in the future, otherwise it is 'open'.",
		"enum": [
		    "closed",
		    "open"
		]
	    }
	},
	"required": [
	    "title",
	    "description",
	    "deadline",
	    "created",
	    "updated",
	    "closed",
	    "state"
	]
    },

    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "http://example.com/milestone.json",
    "$$target": "milestone.json"
}

=== waanlabs/gitcoffee/modules/migration/file_format_testdata/milestones.json
[
  {
      "title": "title_a",
      "description": "description_a",
      "deadline": "1988-04-12T23:20:50.52Z",
      "created": "1985-04-12T23:20:50.52Z",
      "updated": "1986-04-12T23:20:50.52Z",
      "closed": "1987-04-12T23:20:50.52Z",
      "state": "closed"
  },
  {
      "title": "title_b",
      "description": "description_b",
      "deadline": "1998-04-12T23:20:50.52Z",
      "created": "1995-04-12T23:20:50.52Z",
      "updated": "1996-04-12T23:20:50.52Z",
      "closed": null,
      "state": "open"
  }
]
